In [1]:
### Pandas, Numpy CheatSheet

In [2]:
# Data Structure

#### Lists[]
- Mix of Data types
- Are Ordered - can lookup elements by index
- Are Mutable - can be changed

In [3]:
# List Comprehensions

names = ["dumbledore", "beeblebrox", "skywalker", "hermione", "leia"]
capitalized_names = []

for name in names:
  capitalized_names.append(name.title())

capitalized_names = [name.title() for name in names]
capitalized_names

['Dumbledore', 'Beeblebrox', 'Skywalker', 'Hermione', 'Leia']

In [5]:
# adding conditionals

squares = [x ** 2 for x in range(9) if x % 2 == 0]

print(squares)

squares2 = [ x ** 2 if x % 2 == 0 else x + 3 for x in range(9)]

print(squares2)

[0, 4, 16, 36, 64]
[0, 4, 4, 6, 16, 8, 36, 10, 64]


In [7]:
# examples

names = ["Rick S", "Morty Smith", "Summer Smith", "Jerry Smith", "Beth Smith"]
first_names = [name.split(' ')[0] for name in names]
print(first_names)

multiples_3 = [ i * 3 for i in range(1, 21)]
print(multiples_3)

scores = {
    "Rick" : 70,
    "Morty Smith" : 35,
    "Summer Smith" : 82,
    "Jerry Smith" : 23,
    "Beth Smith" : 98
}
passed = [name for name, score in scores.items() if score > 65]
print(passed)

['Rick', 'Morty', 'Summer', 'Jerry', 'Beth']
[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60]
['Rick', 'Summer Smith', 'Beth Smith']


In [8]:
# Lambda Functions 

multiply = lambda x, y : x * y

def multiply(x, y):
  return x * y

multiply(4, 7)

28

In [9]:
# map() - apply lambda function to a list

numbers = [
           [34, 63, 88, 71, 29],
           [90, 78, 51, 27, 45],
           [63, 37, 85, 46, 22],
           [51, 22, 34, 11, 18]
]
mean = lambda num_list : sum(num_list) / len(num_list)
averages = list(map(mean, numbers))

averages = list(map(lambda num_list : sum(num_list) / len(num_list), numbers))

print(averages)

[57.0, 58.2, 50.6, 27.2]


In [10]:
# filter() - apply lambda functions to a list

cities = ["New York City", "Los Angles", "Chicago", "Mountain View", "Denver", "Boston"]
is_short = lambda name : len(name) < 10
short_cities = list(filter(is_short, cities))

short_cities = list(filter(lambda name: len(name) < 10, cities))
print(short_cities)

['Chicago', 'Denver', 'Boston']


In [12]:
# Generators

def my_range(x):
  i = 0
  while i < x:
    yield i
    i += 1

for x in my_range(5):
  print(x)


sq_list = [x**2 for x in range(10)]
sq_iterator = (x**2 for x in range(10))

# example
lessons = ["Why Python Programming", "Data Types and Operators", "Control Flow", "Functions",
           "Scripting"]

def my_enumerate(iterable, start=0):
  i = start
  for element in iterable:
    yield i, element
    i = i + 1

for i, lesson in my_enumerate(lessons, 1):
  print("Lesson {}: {}".format(i, lesson))


# example
def chunker(iterable, size):
  for i in range(0, len(iterable), size):
    yield iterable[i: i+size]

for chunk in chunker(range(25), 4):
  print(list(chunk))

0
1
2
3
4
Lesson 1: Why Python Programming
Lesson 2: Data Types and Operators
Lesson 3: Control Flow
Lesson 4: Functions
Lesson 5: Scripting
[0, 1, 2, 3]
[4, 5, 6, 7]
[8, 9, 10, 11]
[12, 13, 14, 15]
[16, 17, 18, 19]
[20, 21, 22, 23]
[24]


In [13]:
# Create List

list_of_random_things = [1, 3.4, 'a string', True]

list_of_random_things

[1, 3.4, 'a string', True]

In [16]:
# Access list elements

print(list_of_random_things[0])
print(list_of_random_things[-1])

print(list_of_random_things[len(list_of_random_things) - 1])

1
True
True


In [17]:
# Slicing

print(list_of_random_things[1:3])
print(list_of_random_things[:2])
print(list_of_random_things[1:])

[3.4, 'a string']
[1, 3.4]
[3.4, 'a string', True]


In [19]:
# in, not in

print('this' in 'this is a string')
print('in' in 'this is a string')
print('isa' in 'this is a string')

print(5 not in [1, 2, 3, 4, 6])
print(5 in [1, 2,3, 4, 6])

True
True
False
True
False


In [20]:
# Mutable and ordered

my_lst = [1, 2, 3, 4, 5]
my_lst[0] = 0

print(my_lst)

[0, 2, 3, 4, 5]


In [21]:
# length of list

len(list_of_random_things)

4

In [22]:
# smallest and greatest element in list

print(min(list_of_random_things))

print(max(list_of_random_things))

TypeError: ignored

In [23]:
# sorted list

sorted(list_of_random_things)

TypeError: ignored

In [24]:
# join()

name = "-".join(['Grace', 'Kelly'])

print(name)

Grace-Kelly


In [26]:
# Creating a new list

cities = ['new york city', 'mountail view', 'chicago', 'los angeles']
capitalized_cities=[]

for city in cities:
  capitalized_cities.append(city.title())

capitalized_cities

['New York City', 'Mountail View', 'Chicago', 'Los Angeles']

In [27]:
# Adding an element to the end of a list-append()

letters = ['a', 'b', 'c', 'd']
letters.append('z')

print(letters)

['a', 'b', 'c', 'd', 'z']


In [28]:
# Modifying a New List

cities = ['new york city', 'mountain view', 'chicago', 'los angeles']
for index in range(len(cities)):
  cities[index] = cities[index].title()

cities

['New York City', 'Mountain View', 'Chicago', 'Los Angeles']

In [29]:
# Print a formatted string from parameters in list

items = ['first string', 'second string']
html_str = "<ul>\n"
for item in items:
  html_str += "<li>{}</li>\n".format(item)
html_str += "</ul>"

print(html_str)

<ul>
<li>first string</li>
<li>second string</li>
</ul>


In [1]:
# Convert an iterable(tuple, string, set, dictionary) to a list - list()

vowelString = 'aeiou'
print(list(vowelString))

vowelTuple = ('a', 'e', 'i', 'o', 'u')
print(list(vowelTuple))

vowelList = ['a', 'e', 'i', 'o', 'u']
print(list(vowelList))


['a', 'e', 'i', 'o', 'u']
['a', 'e', 'i', 'o', 'u']
['a', 'e', 'i', 'o', 'u']


### Tuples()
- immutable ordered sequences of elements
- They are often used to store related pieces of information. The parentheses are optional when defining tuples

In [2]:
# create tuples

location = (13.4125, 103.866667)

In [3]:
# access tuple

print("Latitulde: ", location[0] )
print("Longtitulde: ", location[1] )

Latitulde:  13.4125
Longtitulde:  103.866667


In [4]:
# tuple packing

dimensions = 52, 40, 100

In [5]:
# tuple unpacking

length, width, height = dimensions

print("The dimensions are {} * {} * {}".format(length, width, height))

The dimensions are 52 * 40 * 100


### Sets{}
- Are unordered - cannot lookup elements by index
- Are mutable - can be changed
- Sets support the in operator the same as lists do
- One application of a set is to quickly remove duplcates from a list
- add elements to sets using the add(), remove elements using the pop()

In [6]:
# create sets

numbers = [1, 2, 6, 3, 1, 1, 6]
unique_nums = set(numbers)

print(unique_nums)

{1, 2, 3, 6}


In [8]:
fruit = {"apple", "banana", "orange", "grapefruit"}

# check for element
print("watermelon" in fruit)

False


In [10]:
# add an element
fruit.add("watermelon")

print(fruit)

{'orange', 'grapefruit', 'watermelon', 'apple', 'banana'}


In [11]:
# remove a random element

print(fruit.pop())
print(fruit)

orange
{'grapefruit', 'watermelon', 'apple', 'banana'}


### Dicts{}
- Are ordered
- Are mutable
- Dictionaries can have keys of any immutable type

In [12]:
# create dict

elements = {"hydrogen" : 1, "helium" : 2, "carbon": 6}

In [13]:
# accessing an element's value
print(elements["helium"])

2


In [14]:
# adding elements

elements["lithium"] = 3

print(elements)

{'hydrogen': 1, 'helium': 2, 'carbon': 6, 'lithium': 3}


In [15]:
# Iterating through a dictionary

for key in elements:
  print(key)

for key, value in elements.items():
  print("Element: {},   Value: {}".format(key, value))


hydrogen
helium
carbon
lithium
Element: hydrogen,   Value: 1
Element: helium,   Value: 2
Element: carbon,   Value: 6
Element: lithium,   Value: 3


In [16]:
# check whether a value is in a dictionary

print("carbon" in elements)

True


In [17]:
# get() looks up values in a dictionary

print(elements.get("dilithium"))
print(elements.get("kryptonite", "There\'s no such element!"))

None
There's no such element!


In [18]:
# Identity Operators

n = elements.get("dilithium")

print(n is None)
print(n is not None)

True
False


In [19]:
# Equality(==) and identity(is)

a = [1, 2, 3]
b = a
c = [1, 2, 3]

print(a==b)
print(a is b)
print(a == c)
print(a is c)

True
True
True
False


In [20]:
# Compound Data Structures

elements = {"hydrogen" : {"number": 1,
                           "weight" : 1.00794,
                           "symbol" : "H"},
             "helium" : {"number" : 2,
                         "weight" : 4.002602,
                         "symbol" : "He"}}

helium = elements["helium"]
hydrogen_weight = elements["helium"]["weight"]
oxygen = {"number":8, "weight":15.999, "symbol": "O"}
elements["oxygen"] = oxygen

print("elements = ", elements)

elements =  {'hydrogen': {'number': 1, 'weight': 1.00794, 'symbol': 'H'}, 'helium': {'number': 2, 'weight': 4.002602, 'symbol': 'He'}, 'oxygen': {'number': 8, 'weight': 15.999, 'symbol': 'O'}}


In [21]:
# Dict frequency counter

words = ['great', 'expectations', 'the', 'adventures', 'of', 'sherlock', 'holmes',
         'the', 'great', 'gasby', 'hamlet', 'adventures', 'of', 'huckleberry', 'fin']

word_counter = {}

for word in words:
  word_counter[word] = word_counter.get(word, 0) + 1

print(word_counter)

{'great': 2, 'expectations': 1, 'the': 2, 'adventures': 2, 'of': 2, 'sherlock': 1, 'holmes': 1, 'gasby': 1, 'hamlet': 1, 'huckleberry': 1, 'fin': 1}


### Numpy

In [22]:
import numpy as np

In [23]:
# create ndarray

x = np.array([1, 2, 3, 4, 5])
print("x = ", x)
print("x has dimensions: ", x.shape)
print("The elements in x are of type: ", x.dtype)

Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Y has dimensions: ", Y.shape)

x =  [1 2 3 4 5]
x has dimensions:  (5,)
The elements in x are of type:  int64
Y has dimensions:  (4, 3)


In [24]:
# create ndarray with dtype

x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype=np.int64)

print(x.dtype)

int64


In [25]:
# save and load

np.save("my_array", x)

y = np.load("my_array.npy")

In [26]:
print(y)

[1 2 3 4 5]


In [27]:
# zeros
X = np.zeros((3, 4))
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
# ones

X = np.ones((3, 2))
print(X)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [29]:
# Full

X = np.full((2, 3), 5)

print(X)

[[5 5 5]
 [5 5 5]]


In [30]:
# identity matrix

X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
# diagonal matrix

X = np.diag([10, 20, 30, 50])
print(X)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [32]:
# Arange

x = np.arange(10)
print(x)

x = np.arange(4, 10)
print(x)

x = np.arange(1, 14, 3)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 1  4  7 10 13]


In [33]:
# linspace

x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [34]:
# Reshape

x = np.arange(20)
x = np.reshape(x, (4, 5))

print(x)

x = np.arange(20).reshape(4, 5)
print(x)

y = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [36]:
# Slicing

X = np.arange(20).reshape(4, 5)
print(X)
Z = X[1:4, 2:5]
print(Z)
Z = X[1:, 2:5]
print(Z)

v = X[2, :]
print(v)
q = X[:, 2]
print(q)
R = X[:, 2:3]
print(R)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[10 11 12 13 14]
[ 2  7 12 17]
[[ 2]
 [ 7]
 [12]
 [17]]


In [37]:
# Random

X = np.random.random((3, 3))
print(X)

X = np.random.randint(4, 15, size=(3, 2))
print(X)

X = np.random.normal(0, 0.1, size=(1000, 1000))
print(X)

[[0.17279154 0.68734424 0.47964372]
 [0.21544133 0.10869713 0.57540352]
 [0.89605555 0.80852461 0.93146212]]
[[ 9 10]
 [13  7]
 [ 4  6]]
[[ 0.0897244  -0.0319906  -0.11203735 ...  0.06686094  0.0826764
  -0.10726758]
 [-0.1333841   0.18496743  0.0126504  ... -0.01186442 -0.10509516
   0.03694815]
 [ 0.26347973 -0.14577214 -0.09552826 ...  0.0056095  -0.1191589
   0.00942612]
 ...
 [-0.09595826  0.03303166  0.07861557 ...  0.27956233 -0.03272833
   0.00456214]
 [-0.06718144  0.05119149  0.24023294 ...  0.07218216  0.12899848
   0.15617001]
 [-0.05521446  0.14555525  0.02148612 ...  0.13488477  0.21280875
  -0.05991406]]


In [38]:
# Mutability

x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)

x[3] = 20
print(x)
x[0,0] = 20
print(x)

[[1 2]
 [3 4]
 [5 6]]


IndexError: ignored

In [39]:
# Delete

x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0, 4])
print(x)

Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Y)

w = np.delete(Y, 0, axis=0)
print(w)

v = np.delete(Y, [0, 2], axis=1)
print(v)


[1 2 3 4 5]
[2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[2]
 [5]
 [8]]


In [40]:
# Append

x = np.append(x, 6)
print(x)

x = np.append(x, [7, 8])
print(x)

v = np.append(Y, [[10, 11, 12]], axis=0)
print(v)

q = np.append(Y, [[13], [14], [15]], axis=1)
print(q)

[2 3 4 6]
[2 3 4 6 7 8]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 13]
 [ 4  5  6 14]
 [ 7  8  9 15]]


In [41]:
# Insert

x = np.array([1, 2, 5, 6, 7])
Y = np.array([[1, 2, 3], [4, 5, 6]])

x = np.insert(x, 2, [3, 4])
w = np.insert(Y, 1, [4, 5, 6], axis=0)
v = np.insert(Y, 1, 5, axis=1)

print(x)
print(Y)
print(w)
print(v)

[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [4 5 6]]
[[1 5 2 3]
 [4 5 5 6]]


In [42]:
# Stacking

x = np.array([1, 2])
Y = np.array([[3, 4], [5, 6]])
z = np.vstack((x, Y))
print(z)
w = np.hstack((Y, x.reshape(2, 1)))
print(w)

[[1 2]
 [3 4]
 [5 6]]
[[3 4 1]
 [5 6 2]]


In [45]:
# Copy

Z = np.copy(X[1:4, 2:5])
print(Z)
W = X[1:4, 2:5].copy()
print(W)

[[ 0.0126504  -0.06280906 -0.03497741]
 [-0.09552826 -0.05440142 -0.04962536]
 [ 0.00431713 -0.08732662  0.09394928]]
[[ 0.0126504  -0.06280906 -0.03497741]
 [-0.09552826 -0.05440142 -0.04962536]
 [ 0.00431713 -0.08732662  0.09394928]]


In [ ]:
# Extract elements along the diagonal

d0 = np.diag(X)
print(d0)

d1 = np.diag(X, k=1)
d2 = np.diag(X, k=-1)

print(d1)
print(d2)

In [47]:
# Find Unique Elements

u = np.unique(X)
print(u)

[-0.48012176 -0.45503754 -0.44617769 ...  0.49270728  0.49694483
  0.52954202]


In [48]:
# Boolean Indexing

X = np.arange(25).reshape(5, 5)
print('The elements in X that are greater than 10: ', X[X >10])
print('The elements in X that less than or equal to 7: ', X[X <= 7])
print('The elements in X that are between 10 and 17: ', X[(X>10) & (X<17)])

X[(X>10) & (X<17)] = -1
print(X)

The elements in X that are greater than 10:  [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7:  [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17:  [11 12 13 14 15 16]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [49]:
# Set Operations

x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print("The elements that are both in x and y: ", np.intersect1d(x, y))
print("The elements that are in x that are not in y: ", np.setdiff1d(x, y))
print("All the elements of x and y: ", np.union1d(x, y))

The elements that are both in x and y:  [2 4]
The elements that are in x that are not in y:  [1 3 5]
All the elements of x and y:  [1 2 3 4 5 6 7 8]


In [51]:
# Sorting

s = np.sort(x)
print(s)

x.sort()

s = np.sort(np.unique(x))
print(s)

s = np.sort(X, axis=0)
print(s)

s = np.sort(X, axis=1)
print(s)

[1 2 3 4 5]
[1 2 3 4 5]
[[-1 -1 -1 -1 -1]
 [ 0 -1  2  3  4]
 [ 5  1  7  8  9]
 [10  6 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [-1 -1 -1 -1 10]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [54]:
# Math Functions

x = np.array([1, 2, 3, 4])
y = np.array([5.5, 6.5, 7.5, 8.5])

print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))

X = np.array([1, 2, 3, 4]).reshape(2, 2)
Y = np.array([5.5, 6.5, 7.5, 8.5]).reshape(2, 2)

print(np.add(X, Y))
print(np.subtract(X, Y))
print(np.multiply(X, Y))
print(np.divide(X, Y))

print(np.exp(x))
print(np.sqrt(x))
print(np.power(x, 2))

[ 6.5  8.5 10.5 12.5]
[-4.5 -4.5 -4.5 -4.5]
[ 5.5 13.  22.5 34. ]
[0.18181818 0.30769231 0.4        0.47058824]
[[ 6.5  8.5]
 [10.5 12.5]]
[[-4.5 -4.5]
 [-4.5 -4.5]]
[[ 5.5 13. ]
 [22.5 34. ]]
[[0.18181818 0.30769231]
 [0.4        0.47058824]]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1.         1.41421356 1.73205081 2.        ]
[ 1  4  9 16]


In [55]:
# Statistical Functions

print("Average of all elements in X: ", X.mean())
print("Average of all elements in the columns of X: ", X.mean(axis=0))
print("Average of all elements in the rows of X: ", X.mean(axis=1))
print()

print("Sum of all elements in X: ", X.sum())
print("Standard Deviation of all elements in X: ", X.std())
print("Median of all elements in X: ", np.median(X))
print("Maximum value of all elements in X: ", X.max())
print("Minimum value of all elements in X: ", X.min())

Average of all elements in X:  2.5
Average of all elements in the columns of X:  [2. 3.]
Average of all elements in the rows of X:  [1.5 3.5]

Sum of all elements in X:  10
Standard Deviation of all elements in X:  1.118033988749895
Median of all elements in X:  2.5
Maximum value of all elements in X:  4
Minimum value of all elements in X:  1


In [57]:
# BroadCasting
print("======X======\n", X)


print(4*X)
print(4+X)
print(4-X)
print(4/X)

x = np.array([1, 2, 3])
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Z = np.array([1, 2, 3]).reshape(3, 1)

print(x + Y)
print(Z + Y)

======X======
 [[1 2]
 [3 4]]
[[ 4  8]
 [12 16]]
[[5 6]
 [7 8]]
[[3 2]
 [1 0]]
[[4.         2.        ]
 [1.33333333 1.        ]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


### Pandas
- Allows the use of labels for rows and columns
- Can calculate rolling statistics on time series data
- Easy handling of NaN values
- is able to load data of different formats into DataFrames
- Can join and merge different datasets together
- It integrates with Numpy and Matplotlib

In [59]:
import pandas as pd

In [60]:
# Series

In [61]:
# create series

groceries = pd.Series(data=[30, 6, 'Yes', 'No'], index=['eggs', 'apples', 'milk', 'bread'])
print(groceries)

eggs       30
apples      6
milk      Yes
bread      No
dtype: object


In [62]:
# shape, size, values, index, ndim

print("Groceries has shape: ", groceries.shape)
print('Groceries has dimension: ', groceries.ndim)
print('Groceries has a total of ', groceries.size, 'elements')
print('The data in Groceries is : ', groceries.values)
print('The index of Groceries is : ', groceries.index)

Groceries has shape:  (4,)
Groceries has dimension:  1
Groceries has a total of  4 elements
The data in Groceries is :  [30 6 'Yes' 'No']
The index of Groceries is :  Index(['eggs', 'apples', 'milk', 'bread'], dtype='object')


In [63]:
# Check whether an index label exists in Series

x = 'banana' in groceries
print(x)

False


In [64]:
# Accessing Elements

print('How many eggs do we need to buy: ', groceries['eggs'])
print("Do we need milk and bread: \n", groceries[['milk', 'bread']])

print("How many eggs and apples do we need to buy: \n", groceries.loc[['eggs', 'apples']])

print('How many eggs and apples do we need to buy: \n', groceries[[0, 1]])
print('Do we need bread: \n', groceries[[-1]])
print('How many eggs do we need to buy: ', groceries[0])
print('Do we need milk and bread: \n', groceries.iloc[[2, 3]])

How many eggs do we need to buy:  30
Do we need milk and bread: 
 milk     Yes
bread     No
dtype: object
How many eggs and apples do we need to buy: 
 eggs      30
apples     6
dtype: object
How many eggs and apples do we need to buy: 
 eggs      30
apples     6
dtype: object
Do we need bread: 
 bread    No
dtype: object
How many eggs do we need to buy:  30
Do we need milk and bread: 
 milk     Yes
bread     No
dtype: object


In [65]:
# Change elements

groceries['eggs'] = 2

In [66]:
# Delete Elements

groceries.drop('apples')
print(groceries)

groceries.drop('apples', inplace=True)

eggs        2
apples      6
milk      Yes
bread      No
dtype: object


In [68]:
# Arithmetic Operations

fruits = pd.Series(data=[10, 6, 3,], index=['apples', 'oranges', 'banana'])

fruits + 2
fruits - 2
fruits * 2
fruits / 2

print(np.exp(fruits))
print(np.sqrt(fruits))
print(np.power(fruits, 2))

print(fruits['banana'] + 2)
print(fruits.iloc[0] - 2)
print(fruits[['apples', 'oranges']] * 2)

apples     22026.465795
oranges      403.428793
banana        20.085537
dtype: float64
apples     3.162278
oranges    2.449490
banana     1.732051
dtype: float64
apples     100
oranges     36
banana       9
dtype: int64
5
8
apples     20
oranges    12
dtype: int64


### DataFrame

In [ ]:
# Axes

df.sum()

df.sum(axis=0)

df.sum(axis=1)